baseurl: /z-edit
theme: jekyll-theme-architect
title: Z-Edit
description: "Smart file editor launcher \u2014 opens files in the right editor based\
  \ on MIME type or extension"
show_downloads: true
github:
  repository_url: https://github.com/pilakkat1964/z-edit
  owner_name: pilakkat1964
  owner_url: https://github.com/pilakkat1964
plugins:
- jekyll-feed
- jekyll-relative-links
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title/
defaults:
- scope:
    path: ''
  values:
    layout: default
relative_links:
  collections: true
keep_files:
- .git
- .github
exclude:
- Makefile
- .gitignore
- .github
- README.md
- DEVELOPMENT.md
parent_url: /z-tools
